In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('cybersecurity_attacks.csv')

print(df.shape)
df.info()

(40000, 25)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Timestamp               40000 non-null  object
 1   Source IP Address       40000 non-null  object
 2   Destination IP Address  40000 non-null  object
 3   Source Port             40000 non-null  int64
 4   Destination Port        40000 non-null  int64
 5   Protocol                40000 non-null  object
 6   Packet Length           40000 non-null  int64
 7   Packet Type             40000 non-null  object
 8   Traffic Type            40000 non-null  object
 9   Payload Data            40000 non-null  object
 10  Malware Indicators      20000 non-null  object
 11  Anomaly Scores          40000 non-null  float64
 12  Alerts/Warnings         19933 non-null  object
 13  Attack Type             40000 non-null  object
 14  Attack Signature        40000 non-null  object
 15  Action Taken            40000 non-null  object
 16  Severity Level          40000 non-null  object
 17  User Information        40000 non-null  object
 18  Device Information      40000 non-null  object
 19  Network Segment         40000 non-null  object
 20  Geo-location Data       40000 non-null  object
 21  Proxy Information       20149 non-null  object
 22  Firewall Logs           20039 non-null  object
 23  IDS/IPS Alerts          19950 non-null  object
 24  Log Source              40000 non-null  object
dtypes: float64(1), int64(3), object(21)
memory usage: 7.6+ MB

In [27]:
df.describe()

        Source Port  Destination Port  Packet Length  Anomaly Scores
count  40000.000000      40000.000000   40000.000000    40000.000000
mean   32970.356450      33150.868650     781.452725       50.113473
std    18560.425604      18574.668842     416.044192       28.853598
min     1027.000000       1024.000000      64.000000        0.000000
25%    16850.750000      17094.750000     420.000000       25.150000
50%    32856.000000      33004.500000     782.000000       50.345000
75%    48928.250000      49287.000000    1143.000000       75.030000
max    65530.000000      65535.000000    1500.000000      100.000000

In [28]:
df.describe(include='object')

,Timestamp,Source IP Address,Destination IP Address,Protocol,Packet Type,Traffic Type,Payload Data,Malware Indicators,Alerts/Warnings,Attack Type,...,Action Taken,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
count,40000,40000,40000,40000,40000,40000,40000,20000,19933,40000,...,40000,40000,40000,40000,40000,40000,20149,20039,19950,40000
unique,39997,40000,40000,3,2,3,40000,1,1,3,...,3,3,32389,32104,3,8723,20148,1,1,2
top,2022-06-11 14:28:15,103.216.15.12,84.9.164.252,ICMP,Control,DNS,Qui natus odio asperiores nam. Optio nobis ius...,IoC Detected,Alert Triggered,DDoS,...,Blocked,Medium,Ishaan Chaudhari,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Segment C,"Ghaziabad, Meghalaya",39.123.165.122,Log Data,Alert Data,Firewall
freq,2,1,1,13429,20237,13376,1,20000,19933,13428,...,13529,13435,6,35,13408,16,2,20039,19950,20116

In [29]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
df['Year'] = df['Timestamp'].dt.year
df['Month'] = df['Timestamp'].dt.month
df['Day'] = df['Timestamp'].dt.day
df['Hour'] = df['Timestamp'].dt.strftime('%H:%M:%S')
df = df.drop(columns=['Timestamp'])

print(df.shape)
df.info()

(40000, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Source IP Address       40000 non-null  object
 1   Destination IP Address  40000 non-null  object
 2   Source Port             40000 non-null  int64
 3   Destination Port        40000 non-null  int64
 4   Protocol                40000 non-null  object
 5   Packet Length           40000 non-null  int64
 6   Packet Type             40000 non-null  object
 7   Traffic Type            40000 non-null  object
 8   Payload Data            40000 non-null  object
 9   Malware Indicators      20000 non-null  object
 10  Anomaly Scores          40000 non-null  float64
 11  Alerts/Warnings         19933 non-null  object
 12  Attack Type             40000 non-null  object
 13  Attack Signature        40000 non-null  object
 14  Action Taken            40000 non-null  object
 15  Severity Level          40000 non-null  object
 16  User Information        40000 non-null  object
 17  Device Information      40000 non-null  object
 18  Network Segment         40000 non-null  object
 19  Geo-location Data       40000 non-null  object
 20  Proxy Information       20149 non-null  object
 21  Firewall Logs           20039 non-null  object
 22  IDS/IPS Alerts          19950 non-null  object
 23  Log Source              40000 non-null  object
 24  Year                    40000 non-null  int32
 25  Month                   40000 non-null  int32
 26  Day                     40000 non-null  int32
 27  Hour                    40000 non-null  object
dtypes: float64(1), int32(3), int64(3), object(21)
memory usage: 8.1+ MB

In [30]:
df.describe()

,Source Port,Destination Port,Packet Length,Anomaly Scores,Year,Month,Day
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000
mean,32970.356450,33150.868650,781.452725,50.113473,2021.411375,6.288275,15.629550
std,18560.425604,18574.668842,416.044192,28.853598,1.085253,3.332979,8.771715
min,1027.000000,1024.000000,64.000000,0.000000,2020.000000,1.000000,1.000000
25%,16850.750000,17094.750000,420.000000,25.150000,2020.000000,3.000000,8.000000
50%,32856.000000,33004.500000,782.000000,50.345000,2021.000000,6.000000,16.000000
75%,48928.250000,49287.000000,1143.000000,75.030000,2022.000000,9.000000,23.000000
max,65530.000000,65535.000000,1500.000000,100.000000,2023.000000,12.000000,31.000000

In [31]:
df.describe(include='object')

,Source IP Address,Destination IP Address,Protocol,Packet Type,Traffic Type,Payload Data,Malware Indicators,Alerts/Warnings,Attack Type,Attack Signature,...,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Hour
count,40000,40000,40000,40000,40000,40000,20000,19933,40000,40000,...,40000,40000,40000,40000,40000,20149,20039,19950,40000,40000
unique,40000,40000,3,2,3,40000,1,1,3,2,...,3,32389,32104,3,8723,20148,1,1,2,32032
top,103.216.15.12,84.9.164.252,ICMP,Control,DNS,Qui natus odio asperiores nam. Optio nobis ius...,IoC Detected,Alert Triggered,DDoS,Known Pattern A,...,Medium,Ishaan Chaudhari,Mozilla/5.0 (compatible; MSIE 6.0; Windows NT ...,Segment C,"Ghaziabad, Meghalaya",39.123.165.122,Log Data,Alert Data,Firewall,00:56:06
freq,1,1,13429,20237,13376,1,20000,19933,13428,20076,...,13435,6,35,13408,16,2,20039,19950,20116,5

In [32]:
df.head()

,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,Malware Indicators,...,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source,Year,Month,Day,Hour
0,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,IoC Detected,...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server,2023,5,30,06:33:58
1,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,IoC Detected,...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall,2020,8,26,07:08:30
2,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,IoC Detected,...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall,2022,11,13,08:23:25
3,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,NaN,...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall,2023,7,2,10:38:46
4,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,NaN,...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall,2023,7,16,13:11:07

In [33]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [34]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)
# Identify columns with null values
columns_with_null = df.columns[df.isnull().any()].tolist()

Missing values in each column:
 Source IP Address             0
Destination IP Address        0
Source Port                   0
Destination Port              0
Protocol                      0
Packet Length                 0
Packet Type                   0
Traffic Type                  0
Payload Data                  0
Malware Indicators        20000
Anomaly Scores                0
Alerts/Warnings           20067
Attack Type                   0
Attack Signature              0
Action Taken                  0
Severity Level                0
User Information              0
Device Information            0
Network Segment               0
Geo-location Data             0
Proxy Information         19851
Firewall Logs             19961
IDS/IPS Alerts            20050
Log Source                    0
Year                          0
Month                         0
Day                           0
Hour                          0
dtype: int64

In [35]:
df['Alerts/Warnings'] = df['Alerts/Warnings'].apply(lambda x: 'unknown' if pd.isna(x) else x)
df['Malware Indicators'] = df['Malware Indicators'].apply(lambda x: 'unknown' if pd.isna(x) else x)
df['Proxy Information'] = df['Proxy Information'].apply(lambda x: 'unknown' if pd.isna(x) else x)
df['Firewall Logs'] = df['Firewall Logs'].apply(lambda x: 'unknown' if pd.isna(x) else x)
df['IDS/IPS Alerts'] = df['IDS/IPS Alerts'].apply(lambda x: 'unknown' if pd.isna(x) else x)

print(df.isnull().sum())

Source IP Address         0
Destination IP Address    0
Source Port               0
Destination Port          0
Protocol                  0
Packet Length             0
Packet Type               0
Traffic Type              0
Payload Data              0
Malware Indicators        0
Anomaly Scores            0
Alerts/Warnings           0
Attack Type               0
Attack Signature          0
Action Taken              0
Severity Level            0
User Information          0
Device Information        0
Network Segment           0
Geo-location Data         0
Proxy Information         0
Firewall Logs             0
IDS/IPS Alerts            0
Log Source                0
Year                      0
Month                     0
Day                       0
Hour                      0
dtype: int64